clientVerseGit/force-app/main/default/objects/List__c/List__c.object-meta.xml
<CustomObject>
    <description>List of contacts, accounts, lists, or campaigns for targeting, segmentation, and event and campaign management.</description>
    <label>List</label>
    <nameField>
        <label>List Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

clientVerseGit/force-app/main/default/objects/List__c/fields/List_Member_Mapping__c.field-meta.xml
<CustomField>
    <fullName>List_Member_Mapping__c</fullName>
    <label>List Member Mapping</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

clientVerseGit/force-app/main/default/classes/ListSelector.cls
public with sharing class ListSelector extends fflib_SObjectSelector {

    public ListSelector() {
        super();
    }

    public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField>{
            List__c.Id,
            List__c.List_Member_Mapping__c
        };
    }

    public Schema.SObjectType getSObjectType() {
        return List__c.SObjectType;
    }

    public List<List__c> selectByIds(Set<Id> ids) {
        return (List<List__c>) selectSObjectsById(ids);
    }
}